add TEST_FAIL_FLAG

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -30,6 +30,7 @@ test_script:
       }
     }"
     }
+    TEST_FAIL_FLAG=false
     WELCOME="^Welcome to .NET Core"
     for ver in $(dotnet --list-sdks|cut -f1 -d' '); do
         TMP_DIR=$(mktemp -d)
@@ -42,12 +43,17 @@ test_script:
             echo "---- OUTPUT ----"
             echo "$OUTPUT"
             echo "---- OUTPUT ----"
-            return 2
+            TEST_FAIL_FLAG=true
           fi
         done <<< "${OUTPUT}"
         popd &&
         rm -rf "${TMP_DIR}"
     done
+    if $TEST_FAIL_FLAG; then
+        echo "${RED}Test failed!${NC}"
+        exit 2
+    fi
+    
  - sh: ls -ltra "$HOME/.dotnet/"
  
 build: off
